apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: venkatlekkala/py-flask-app
          ports:
            - containerPort: 4000
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: secret-basic
                  key: DB_URL
