apiVersion: v1
kind: Secret
metadata:
  name: secret-basic
type: Opaque
stringData:
  POSTGRES_USER: postgres # required field for kubernetes.io/basic-auth
  POSTGRES_PASSWORD: postgres # required field for kubernetes.io/basic-auth
  POSTGRES_DB: postgres
  DB_URL: "postgresql://postgres:postgres@flask-db-service:5432/postgres"
